" Compatibility {{{1
set nocompatible
filetype off
set encoding=utf-8


" Bundle {{{1

source ~/.vim/keybindings.vim

call plug#begin('~/.vim/bundle')
source ~/.vim/plug-config.vim
call plug#end()


" Basic configuration {{{1
" I'm British!
set spelllang=en_gb
" Hide buffers that aren't visible
set hidden
" Don't update the display while executing macros
set lazyredraw
" Wrap lines when vim can't display all of it
set wrap
" Highlight search matches
set hlsearch
" Only match case sensitive when upper case letters are used in searches
set smartcase
" Show numbers in the left hand margin
set number
" Hide mouse pointer when typing
set mousehide
" Only syntax highlight to this number of columns
" prevents slow performance when working on files that are composed of a
" single very long line
set synmaxcol=1024
" Smartly indent the next line, similar to `cindent`. If `cindent` is
" already on then `smartindent` has no effect.
set smartindent
" Expand tab character into the corresponding number of spaces
set expandtab
" Tabs count for 4 spaces
set tabstop=4
" Number of spaces to use for each step of autoindent
" 0 = use the value of `tabstop`
set shiftwidth=0
" `virtualedit` enables editing a file in space where there is no space
" think of block selecting across multiple lines of different length
" `all` enables virtualediting in block and insert mode.
set virtualedit=all
" Indent things to the nearest indent stop (effects < > ops)
set shiftround
" Don't leave byte-order-marks at the start of files, people don't
" like them
set nobomb
filetype plugin indent on
syntax on
" Fold based on fold-markers
set foldmethod=marker


" Appearance {{{1
" Prevent NeoSolarized from going yellow when opening
" neovim in gnome-terminal
set termguicolors
silent! colorscheme NeoSolarized
let _time = strftime("%H")
if _time > 8 && _time < 20
    set background=light
else
    set background=dark
endif
