name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test dotfiles linking and pre/post installation steps
    steps:
      - name: Install tools
        run: sudo apt-get update -y && sudo apt-get install fish git stow python3 python3-pip vim 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove bashrc*
        run: rm -rf ~/.bash*
      - name: Test installing dotfiles
        run: ./install-all.sh

