name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test dotfiles linking and pre/post installation steps
    steps:
      - run: apt-get update -y && apt-get install fish git stow python3 python3-pip vim 
      - run: ./install-all.sh

